###########################################
###Relacionado a Spring - Hibernate , profile y admin
###########################################

spring:
  profiles:
    active: dev    
        
#Admin Boot    
  boot:
    admin:
      #url:  http://localhost:1111
      #username: admin
      #password: 1234

#Info DB    
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.10.2.97;databaseName=CoreSpringWeb
    username: local
    password: local2017
     
#Info Persistencia JPA y Hibernate                      
  jpa:    
    properties:
      hibernate:                             
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        naming_strategy:  org.hibernate.cfg.DefaultNamingStrategy
        #naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy        
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        show_sql: true
        format_sql: true          
        packagesToScan: erp.realcoresystems.pe.model
               

#Atributos personalizados para la documentacion del API con SWAGGER

swagger:
  info:
    title: Spring Boot REST API XXX
    description: Spring Boot REST API
  

###########################################
####Relacionado al despliegue  PROFILE DEV
###########################################               
---
spring:
  profiles: dev        
  application:
    name: comercial-dev        

server:
  port: ${vcap.application.port:8150}

   
###########################################
####Relacionado al despliegue  PROFILE PUBLICADO - I
###########################################     
---
spring:
  profiles: pub
  application:
    name: comercial-pub
    
#Data Source
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.10.2.97;databaseName=CoreSpringWeb
    username: local
    password: local2017
 #Tunear parametros para reconecci贸n y tiempo fuera de conexi贸n
    #removeAbandonedTimeout: 1800
    #removeAbandoned: true     
    testOnBorrow: true
    validation-query: SELECT 1     
    validation-query-timeout: 60000
    logAbandoned: true
    minEvictableIdleTimeMillis: 60000    
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1
    test-on-connect: true    
        
     
#Info Persistencia JPA y Hibernate                      
  jpa:    
    properties:
      hibernate:                             
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        naming_strategy:  org.hibernate.cfg.DefaultNamingStrategy       
        dialect: org.hibernate.dialect.SQLServer2008Dialect       
        show_sql: true
        format_sql: true          
        packagesToScan: erp.realcoresystems.pe.model

server:
  port: ${vcap.application.port:8055}

###########################################
####Relacionado al despliegue  PROFILE PUBLICADO - II
###########################################     
---
spring:
  profiles: pub-icpna
  application:
    name: comercial-pub     
    
#Data Source
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.10.2.97:1414;databaseName=ICPNA
    username: local
    password: local2017
 #Tunear parametros para reconecci贸n y tiempo fuera de conexi贸n
    #removeAbandonedTimeout: 1800
    #removeAbandoned: true     
    testOnBorrow: true
    validation-query: SELECT 1     
    validation-query-timeout: 60000
    logAbandoned: true
    minEvictableIdleTimeMillis: 60000    
    maxWait: 60000
    maxIdle: 1
    minIdle: 0
    maxActive: 50
    initialSize: 1
    test-on-connect: true    
        
     
#Info Persistencia JPA y Hibernate                      
  jpa:    
    properties:
      hibernate:                             
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        naming_strategy:  org.hibernate.cfg.DefaultNamingStrategy       
        dialect: org.hibernate.dialect.SQLServer2008Dialect       
        show_sql: true
        format_sql: true          
        packagesToScan: erp.realcoresystems.pe.model

server:
  port: ${vcap.application.port:8050}

